vlog -work work P:/DSD/Projects/g48_Lab_5/simulation/modelsim/g48_music_box.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.g48_music_box_vlg_vec_tst
onerror {resume}
add wave {g48_music_box_vlg_vec_tst/i1/d2}
add wave {g48_music_box_vlg_vec_tst/i1/d2[6]}
add wave {g48_music_box_vlg_vec_tst/i1/d2[5]}
add wave {g48_music_box_vlg_vec_tst/i1/d2[4]}
add wave {g48_music_box_vlg_vec_tst/i1/d2[3]}
add wave {g48_music_box_vlg_vec_tst/i1/d2[2]}
add wave {g48_music_box_vlg_vec_tst/i1/d2[1]}
add wave {g48_music_box_vlg_vec_tst/i1/d2[0]}
add wave {g48_music_box_vlg_vec_tst/i1/d3}
add wave {g48_music_box_vlg_vec_tst/i1/d3[6]}
add wave {g48_music_box_vlg_vec_tst/i1/d3[5]}
add wave {g48_music_box_vlg_vec_tst/i1/d3[4]}
add wave {g48_music_box_vlg_vec_tst/i1/d3[3]}
add wave {g48_music_box_vlg_vec_tst/i1/d3[2]}
add wave {g48_music_box_vlg_vec_tst/i1/d3[1]}
add wave {g48_music_box_vlg_vec_tst/i1/d3[0]}
add wave {g48_music_box_vlg_vec_tst/i1/init}
add wave {g48_music_box_vlg_vec_tst/i1/looping}
add wave {g48_music_box_vlg_vec_tst/i1/octave_i}
add wave {g48_music_box_vlg_vec_tst/i1/pause}
add wave {g48_music_box_vlg_vec_tst/i1/reset}
add wave {g48_music_box_vlg_vec_tst/i1/slct}
add wave {g48_music_box_vlg_vec_tst/i1/start}
add wave {g48_music_box_vlg_vec_tst/i1/stop}
add wave {g48_music_box_vlg_vec_tst/i1/trigger_o}
add wave {g48_music_box_vlg_vec_tst/i1/bpm}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[7]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[6]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[5]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[4]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[3]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[2]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[1]}
add wave {g48_music_box_vlg_vec_tst/i1/bpm[0]}
add wave {g48_music_box_vlg_vec_tst/i1/clk_50}
add wave {g48_music_box_vlg_vec_tst/i1/d0}
add wave {g48_music_box_vlg_vec_tst/i1/d0[6]}
add wave {g48_music_box_vlg_vec_tst/i1/d0[5]}
add wave {g48_music_box_vlg_vec_tst/i1/d0[4]}
add wave {g48_music_box_vlg_vec_tst/i1/d0[3]}
add wave {g48_music_box_vlg_vec_tst/i1/d0[2]}
add wave {g48_music_box_vlg_vec_tst/i1/d0[1]}
add wave {g48_music_box_vlg_vec_tst/i1/d0[0]}
add wave {g48_music_box_vlg_vec_tst/i1/d1}
add wave {g48_music_box_vlg_vec_tst/i1/d1[6]}
add wave {g48_music_box_vlg_vec_tst/i1/d1[5]}
add wave {g48_music_box_vlg_vec_tst/i1/d1[4]}
add wave {g48_music_box_vlg_vec_tst/i1/d1[3]}
add wave {g48_music_box_vlg_vec_tst/i1/d1[2]}
add wave {g48_music_box_vlg_vec_tst/i1/d1[1]}
add wave {g48_music_box_vlg_vec_tst/i1/d1[0]}
add wave {g48_music_box_vlg_vec_tst/i1/I2C_SDAT}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[0]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[1]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[2]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[3]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[4]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[5]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[6]~result}
add wave {g48_music_box_vlg_vec_tst/i1/FL_DQ[7]~result}
add wave {g48_music_box_vlg_vec_tst/i1/beat}
add wave {g48_music_box_vlg_vec_tst/i1/AUD_MCLK}
add wave {g48_music_box_vlg_vec_tst/i1/AUD_BCLK}
add wave {g48_music_box_vlg_vec_tst/i1/AUD_DACDAT}
add wave {g48_music_box_vlg_vec_tst/i1/AUD_DACLRCK}
add wave {g48_music_box_vlg_vec_tst/i1/I2C_SCLK}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[0]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[1]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[2]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[3]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[4]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[5]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[6]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[7]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[8]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[9]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[10]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[11]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[12]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[13]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[14]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[15]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[16]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[17]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[18]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[19]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[20]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_ADDR[21]}
add wave {g48_music_box_vlg_vec_tst/i1/FL_CE_N}
add wave {g48_music_box_vlg_vec_tst/i1/FL_OE_N}
add wave {g48_music_box_vlg_vec_tst/i1/FL_WE_N}
add wave {g48_music_box_vlg_vec_tst/i1/FL_RST_N}
run -all
